/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

/**
 *
 * @author Pichau
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanelInternoFrame = new javax.swing.JPanel();
        jLabelNotasPainel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabelCadastrarProfessorPainel = new javax.swing.JLabel();
        jLabelCadastroAlunoPainel = new javax.swing.JLabel();
        jButtonCadastrarProf = new javax.swing.JButton();
        jButtonCadastrarAluno = new javax.swing.JButton();
        jLabelFundoBemVindo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonSairPainel = new javax.swing.JButton();
        jLabelFundoPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadastroAluno = new javax.swing.JMenuItem();
        jMenuItemCadastroProfessor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemAtalho = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Background.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameBemVindo.setResizable(true);
        jInternalFrameBemVindo.setTitle("Bem Vindo");
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jPanelInternoFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInternoFrame.setLayout(null);

        jLabelNotasPainel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNotasPainel.setText("Notas");
        jPanelInternoFrame.add(jLabelNotasPainel);
        jLabelNotasPainel.setBounds(590, 170, 60, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Notas.png"))); // NOI18N
        jPanelInternoFrame.add(jButton2);
        jButton2.setBounds(490, 210, 240, 210);

        jLabelCadastrarProfessorPainel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCadastrarProfessorPainel.setText("Cadastro Professor");
        jPanelInternoFrame.add(jLabelCadastrarProfessorPainel);
        jLabelCadastrarProfessorPainel.setBounds(240, 40, 140, 40);

        jLabelCadastroAlunoPainel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCadastroAlunoPainel.setText("Cadastro Aluno");
        jPanelInternoFrame.add(jLabelCadastroAlunoPainel);
        jLabelCadastroAlunoPainel.setBounds(40, 40, 110, 40);

        jButtonCadastrarProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/professor.png"))); // NOI18N
        jButtonCadastrarProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarProfActionPerformed(evt);
            }
        });
        jPanelInternoFrame.add(jButtonCadastrarProf);
        jButtonCadastrarProf.setBounds(230, 80, 150, 340);

        jButtonCadastrarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/aluno.png"))); // NOI18N
        jButtonCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarAlunoActionPerformed(evt);
            }
        });
        jPanelInternoFrame.add(jButtonCadastrarAluno);
        jButtonCadastrarAluno.setBounds(20, 80, 140, 340);

        jLabelFundoBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/backgroung tela principal.jpg"))); // NOI18N
        jPanelInternoFrame.add(jLabelFundoBemVindo);
        jLabelFundoBemVindo.setBounds(10, 0, 870, 470);

        jInternalFrameBemVindo.getContentPane().add(jPanelInternoFrame);
        jPanelInternoFrame.setBounds(0, 80, 870, 460);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Gerenciamento");
        jInternalFrameBemVindo.getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 20, 130, 22);

        jButtonSairPainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/exit.png"))); // NOI18N
        jButtonSairPainel.setToolTipText("Fechar Tela Inicial");
        jButtonSairPainel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairPainelActionPerformed(evt);
            }
        });
        jInternalFrameBemVindo.getContentPane().add(jButtonSairPainel);
        jButtonSairPainel.setBounds(800, 20, 50, 50);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(0, 80, 890, 570);

        jLabelFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/backgroung tela principal.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoPrincipal);
        jLabelFundoPrincipal.setBounds(0, 0, 900, 713);

        jMenuCadastro.setText("Cadastros");

        jMenuItemCadastroAluno.setText("Aluno");
        jMenuItemCadastroAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroAlunoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroAluno);

        jMenuItemCadastroProfessor.setText("Professor");
        jMenuItemCadastroProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroProfessorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroProfessor);

        jMenuBar1.add(jMenuCadastro);

        jMenu3.setText("Ferramentas");

        jMenuItemAtalho.setText("Atalhos");
        jMenuItemAtalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtalhoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemAtalho);

        jMenuBar1.add(jMenu3);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(916, 739));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastroProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroProfessorActionPerformed
        // TODO add your handling code here:
        FormProfessor tela = new FormProfessor();
        tela.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemCadastroProfessorActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemCadastroAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCadastroAlunoActionPerformed

    private void jButtonCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadastrarAlunoActionPerformed

    private void jButtonCadastrarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarProfActionPerformed
        // TODO add your handling code here:
        FormProfessor tela = new FormProfessor();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarProfActionPerformed

    private void jButtonSairPainelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairPainelActionPerformed
        // TODO add your handling code here:
        jInternalFrameBemVindo.dispose();
    }//GEN-LAST:event_jButtonSairPainelActionPerformed

    private void jMenuItemAtalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtalhoActionPerformed
        // TODO add your handling code here:
        TelaPrincipal tela= new TelaPrincipal();
        tela.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jMenuItemAtalhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCadastrarAluno;
    private javax.swing.JButton jButtonCadastrarProf;
    private javax.swing.JButton jButtonSairPainel;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCadastrarProfessorPainel;
    private javax.swing.JLabel jLabelCadastroAlunoPainel;
    private javax.swing.JLabel jLabelFundoBemVindo;
    private javax.swing.JLabel jLabelFundoPrincipal;
    private javax.swing.JLabel jLabelNotasPainel;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItemAtalho;
    private javax.swing.JMenuItem jMenuItemCadastroAluno;
    private javax.swing.JMenuItem jMenuItemCadastroProfessor;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelInternoFrame;
    // End of variables declaration//GEN-END:variables

    void isVisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setVisible() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
